apiVersion: apps/v1
kind: Deployment
metadata:
  name: fanda-fe-deploy
  namespace: fanda-fe
  labels:
    app: fanda-fe
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fanda-fe
  template:
    metadata:
      labels:
        app: fanda-fe
        version: v1
    spec:
      containers:
      - name: fanda-fe
        image: 192.168.2.111/fanda-fe/frontend:53
        ports:
        - containerPort: 80
          name: http
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 10
      imagePullSecrets: 
      - name: harbor-secret
