apiVersion: apps/v1
kind: Deployment
metadata:
  name: fanda-fe-deploy
  namespace: fanda-fe
  labels:
    app: fanda-fe
    version: v1
    component: frontend
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: fanda-fe
  template:
    metadata:
      labels:
        app: fanda-fe
        version: v1
        component: frontend
    spec:
      containers:
      - name: fanda-fe
        image: 192.168.2.111/fanda-fe/frontend:3e6db2c0
        imagePullPolicy: Always 
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        
        livenessProbe:
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        
        readinessProbe:
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 2
        
        env:
        - name: TZ
          value: "Asia/Seoul"
      
      dnsPolicy: ClusterFirst
      restartPolicy: Always